fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "refresh_network",
            "cached_devices",
            "update_device",
            "get_settings",
            "save_setting",
            "list_tasks",
            "task_detail",
            "submit_repair",
            "app_info",
            "open_remote_desktop",
            "remote_connections",
            "pair_remote",
            "remote_capabilities",
            "submit_remote",
            "remote_histories",
            "remote_detail",
            "cancel_remote",
            "download_remote",
            "local_agent_status",
            "choose_agent_directory",
            "start_local_agent",
            "local_agent_pairing",
            "revoke_controller",
            "stop_local_agent",
            "agent_autostart",
            "set_agent_autostart",
        ]),
    ))
    .expect("failed to build Tauri resources");
}
