import { isDesktop } from '../api';
import type { Task } from '../types';
import type { TailTaskState } from '../useTailTask';
import { EmptyState,formatTime,Modal,TaskStatus } from './Common';
import { Icon } from './Icon';

export function TaskTable({tasks,onOpen}:{tasks:Task[];onOpen:(id:string)=>void}) {
  return <div className="table-wrap"><table className="task-table"><thead><tr><th>任务名称</th><th>状态</th><th>创建时间</th><th>目标</th><th>进度 / 结果</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{tasks.map(task=><tr key={task.id}><td><button className="task-name" onClick={()=>onOpen(task.id)}><span className="task-icon"><Icon name="database"/></span><span><strong>{task.label}</strong><small>{task.id.slice(0,8)}</small></span></button></td><td><TaskStatus task={task}/></td><td className="nowrap"><time>{formatTime(task.created_at)}</time></td><td className="nowrap">本机应用</td><td className="task-result"><span title={task.persistence_warning||task.result||''}>{task.persistence_warning?'结果未能保存，请查看详情':task.result|| (task.state==='running'?'正在执行预定义修复':'等待执行')}</span>{task.state==='running'&&!task.persistence_warning&&<div className="activity-bar" role="progressbar" aria-label="任务正在执行"><span/></div>}</td><td><button className="icon-button" aria-label={'查看任务 '+task.id} onClick={()=>onOpen(task.id)}><Icon name="chevron" size={17}/></button></td></tr>)}</tbody></table></div>;
}
export function RecentTasks({state,onAll,onRepair}:{state:TailTaskState;onAll:()=>void;onRepair:()=>void}) {
  return <section className="panel recent-tasks"><div className="panel-title"><h2>最近的本机任务</h2><button className="text-button" onClick={onAll}>查看全部 <Icon name="arrow" size={16}/></button></div>{state.recent.length?<TaskTable tasks={state.recent} onOpen={state.openTask}/>:<div className="empty-inline"><span className="task-icon"><Icon name="database"/></span><div><strong>还没有任务记录</strong><p>执行一次本机数据库检查，结果会保存在这里。</p></div><button className="text-button push-right" onClick={onRepair}>前往本机修复 <Icon name="arrow" size={16}/></button></div>}</section>;
}
export function Tasks({state,onRepair}:{state:TailTaskState;onRepair:()=>void}) {
  return <section className="panel"><div className="panel-title"><h2>任务记录</h2><button disabled={!isDesktop||state.tasksLoading} onClick={()=>void state.loadTasks()}><Icon name="refresh" size={17}/>刷新记录</button></div>{state.tasks.length?<TaskTable tasks={state.tasks} onOpen={state.openTask}/>:<EmptyState icon="tasks" title={state.tasksLoading?'读取记录中…':'暂无任务记录'} action={<button onClick={onRepair}>前往本机修复</button>}>本机修复的状态与结果会保存在这里，重新打开应用后仍可查看。</EmptyState>}<div className="pagination"><span className="muted">每页最多 50 条 · 本地持久保存</span><div><button disabled={state.taskPage===0} onClick={()=>state.setTaskPage(p=>p-1)}>上一页</button><span>第 {state.taskPage+1} 页</span><button disabled={state.tasks.length<50} onClick={()=>state.setTaskPage(p=>p+1)}>下一页</button></div></div></section>;
}
export function TaskDetailModal({state}:{state:TailTaskState}) {
  const detail=state.detail;
  return <Modal title="任务详情" onClose={state.closeTask} wide>{detail&&<><div className="task-detail-heading"><div><h3>{detail.task.label}</h3><p>作用范围：本机 xiangwriter远程器 应用数据</p></div><TaskStatus task={detail.task}/></div><div className="task-id"><span>任务编号</span><code>{detail.task.id}</code></div>{detail.task.persistence_warning&&<div className="alert alert-error" role="alert">{detail.task.persistence_warning}</div>}<div className="result-box"><span className="eyebrow">执行结果</span><p>{detail.task.result|| (detail.task.persistence_warning?'状态待核实，未自动重试。':'正在等待实际结果…')}</p></div><h3 className="section-label">执行记录</h3><ol className="timeline">{detail.events.map(event=><li key={event.seq}><span className={'timeline-dot '+(event.kind==='succeeded'?'done':'')}/><div><strong>{event.message}</strong><time>{formatTime(event.occurred_at)}</time></div></li>)}</ol></>}{state.detailError&&<div className="alert alert-error" role="alert"><div><strong>任务详情暂时无法读取</strong><p>{state.detailError}</p></div><button onClick={()=>void state.readDetail(state.detailId!)}>重试读取</button></div>}{!detail&&!state.detailError&&<EmptyState icon="tasks" title="正在读取任务">请稍候…</EmptyState>}<div className="modal-actions"><button onClick={state.closeTask}>关闭</button></div></Modal>;
}
